# Generated by Django 4.0 on 2022-01-13 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant1', models.CharField(blank=True, help_text='при наявності', max_length=100, verbose_name='Варiант 1')),
                ('variant2', models.CharField(blank=True, help_text='при наявності', max_length=100, verbose_name='Варiант 2')),
                ('variant3', models.CharField(blank=True, help_text='при наявності', max_length=100, verbose_name='Варiант 3')),
                ('variant4', models.CharField(blank=True, help_text='при наявності', max_length=100, verbose_name='Варiант 4')),
                ('variant5', models.CharField(blank=True, help_text='при наявності', max_length=100, verbose_name='Варiант 5')),
                ('variant6', models.CharField(blank=True, help_text='при наявності', max_length=100, verbose_name='Варiант 6')),
            ],
            options={
                'verbose_name': 'Варiанти відповіді',
                'verbose_name_plural': 'Варiанти відповіді',
            },
        ),
        migrations.CreateModel(
            name='Correct_answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer1', models.CharField(help_text='Основна відповідь', max_length=100, verbose_name='Правильна відповідь 1')),
                ('correct_answer2', models.CharField(blank=True, help_text='при наявності', max_length=100, verbose_name='Правильна відповідь 2')),
                ('correct_answer3', models.CharField(blank=True, help_text='при наявності', max_length=100, verbose_name='Правильна відповідь 3')),
                ('correct_answer4', models.CharField(blank=True, help_text='при наявності', max_length=100, verbose_name='Правильна відповідь 4')),
                ('correct_answer5', models.CharField(blank=True, help_text='при наявності', max_length=100, verbose_name='Правильна відповідь 5')),
            ],
            options={
                'verbose_name': 'Правильна відповідь',
                'verbose_name_plural': 'Правильні відповіді',
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('S', 'Коротка відповідь'), ('SC', 'Одиночний вибір'), ('MC', 'Множинний вибір'), ('G', 'Grid')], default='S', max_length=2, verbose_name='Тип питання')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Тип питання',
                'verbose_name_plural': 'Типи питань',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва тесту')),
                ('quantity_questions', models.PositiveSmallIntegerField(verbose_name='Кількість питань')),
                ('time_for_test', models.PositiveSmallIntegerField(default=60, help_text='Час тесту в хвилинах', verbose_name='Час тесту')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тести',
            },
        ),
        migrations.CreateModel(
            name='TestedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('login', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Користувач тесту',
                'verbose_name_plural': 'Користувачі тесту',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(blank=True)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.test')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.testeduser')),
            ],
            options={
                'verbose_name': 'Результат тесту',
                'verbose_name_plural': 'Результати тесту',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_image', models.ImageField(blank=True, upload_to=None)),
                ('max_points', models.IntegerField()),
                ('answer_variants', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.answer_variants')),
                ('correct_answers', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='test_app.correct_answers')),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_app.questiontype')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.test')),
            ],
            options={
                'verbose_name': 'Питання',
                'verbose_name_plural': 'Питання',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=40)),
                ('answer_time', models.IntegerField(blank=True)),
                ('point', models.IntegerField(blank=True)),
                ('question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.testeduser')),
            ],
            options={
                'verbose_name': 'Відповідь користувача',
                'verbose_name_plural': 'Відповіді користувача',
            },
        ),
    ]
