# Generated by Django 4.0 on 2022-01-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_alter_answer_options_test_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='questiontype',
            options={'verbose_name': 'Question type', 'verbose_name_plural': 'Question type'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Tests'},
        ),
        migrations.RenameField(
            model_name='result',
            old_name='persent',
            new_name='percent',
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='name',
            field=models.CharField(choices=[('S', 'Вписати відповідь'), ('SC', 'Одиночний вибір'), ('MC', 'Множинний вибір'), ('G', 'Grid')], default='S', max_length=2, unique=True, verbose_name='Тип питання'),
        ),
        migrations.AlterField(
            model_name='test',
            name='quantity_questions',
            field=models.PositiveSmallIntegerField(help_text='Скільки питань видавати для тесту?', verbose_name='Кількість питань'),
        ),
    ]
