# Generated by Django 4.0 on 2022-02-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_alter_question_options_alter_questiontype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer_variants',
            options={'verbose_name': 'Answer variants', 'verbose_name_plural': 'Answer variants'},
        ),
        migrations.AlterModelOptions(
            name='correct_answers',
            options={'verbose_name': 'correct answer', 'verbose_name_plural': 'correct answers'},
        ),
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, help_text='Інформація для користувача'),
        ),
    ]
