# Generated by Django 4.0 on 2022-02-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_alter_answer_variants_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='by_text',
            field=models.TextField(blank=True, help_text='Для виводу по закінченню тесту'),
        ),
    ]
