# Generated by Django 4.0 on 2022-02-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_alter_correct_answers_correct_answer5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correct_answers',
            name='correct_answer2',
            field=models.CharField(blank=True, help_text='при наявності', max_length=100, null=True, verbose_name='Правильна відповідь 2'),
        ),
        migrations.AlterField(
            model_name='correct_answers',
            name='correct_answer3',
            field=models.CharField(blank=True, help_text='при наявності', max_length=100, null=True, verbose_name='Правильна відповідь 3'),
        ),
        migrations.AlterField(
            model_name='correct_answers',
            name='correct_answer4',
            field=models.CharField(blank=True, help_text='при наявності', max_length=100, null=True, verbose_name='Правильна відповідь 4'),
        ),
    ]
